# Generated by Django 3.1.1 on 2020-09-02 16:48

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import multiselectfield.db.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('date_obtained', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=255)),
                ('school', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('online_course', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.CharField(blank=True, choices=[('jakarta', 'Jakarta'), ('new_york', 'New York'), ('tokyo', 'Tokyo'), ('rome', 'Rome'), ('san_francisco', 'San Francisco')], max_length=250, null=True)),
                ('sections', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('work_experience', 'Experience'), ('education', 'Education'), ('certifications', 'Certifications'), ('courses', 'Courses'), ('projects', 'Projects'), ('publications', 'Publications'), ('skills', 'Skills'), ('languages', 'Languages'), ('hobbies', 'Hobbies'), ('custom_section', 'Custom Section')], max_length=110, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('achievements', tinymce.models.HTMLField(blank=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
            options={
                'verbose_name_plural': 'Work Experience',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('competency', models.IntegerField(blank=True, choices=[('', '-----'), (1, 'Below Average'), (2, 'Average'), (3, 'Good'), (4, 'Excellent')], null=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('publication_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
            options={
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('competency', models.IntegerField(blank=True, choices=[('', '-----'), (1, 'Beginner'), (2, 'Elementary'), (3, 'Intermediate'), (4, 'Upper-Intermediate'), (5, 'Advanced'), (6, 'Native')], null=True)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
                ('write', models.BooleanField(blank=True, default=False, null=True)),
                ('speak', models.BooleanField(blank=True, default=False, null=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('degree', models.CharField(blank=True, max_length=255)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True)),
                ('cv', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv')),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['-end_date'],
            },
        ),
    ]
