# Generated by Django 3.1.1 on 2020-09-02 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsection',
            name='cv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv'),
        ),
        migrations.AddField(
            model_name='course',
            name='cv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv'),
        ),
        migrations.AddField(
            model_name='certification',
            name='cv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.cv'),
        ),
    ]
